# Generated by Django 6.0.1 on 2026-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_category_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-question time limit in seconds', null=True),
        ),
    ]
