# Generated by Django 6.0.1 on 2026-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_time_limit_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional explanation shown after the exam is submitted'),
        ),
    ]
